### PR TITLE
Handle prepare for http only

### PR DESCRIPTION
**Pull request by fabiancook**

### CODE REVIEW

**Comment by fabiancook** [comment]
Related to https://github.com/zmxv/react-native-sound/pull/205#discussion_r122413352

**Comment by trepidity** [comment]
@fabiancook would you like for me to merge this into the unstable branch for testing?

**Comment by fabiancook** [comment]
Sorry, I no longer actively work on the project that utilizes this module.

**Comment by paulmelnikow** [comment]
Thanks for contributing this change, and sorry it's languished so long!

The code referred to by the comment https://github.com/zmxv/react-native-sound/pull/205#discussion_r122413352 is now being handled differently. There is probably room to improve this code, though the specific change suggested here is out of date.

https://github.com/zmxv/react-native-sound/blob/1ebf2d296eafba6e6e314188caef715d6ea23ade/android/src/main/java/com/zmxv/RNSound/RNSoundModule.java#L141-L145

**Pull request closed without merging**
