### PR TITLE
Fix Android every Sound instance can be released

### PR DESCRIPTION
**Pull request by leechan**
In some Android devices only the first time can loaded success, then new Sound not invoke loaded callback forever. I check this code, the issue is about sound release. So I change it, make every Sound instance can be released. It works for me.

### CODE REVIEW

**Comment by trepidity** [comment]
@gvenk didn't you try this already?

**Comment by kasajei** [comment]
In Progress? I need this PR.

**Comment by trepidity** [comment]
@kasajei have you tested the PR and does it work for you?

**Comment by paulmelnikow** [comment]
Hi! Thanks for this. The callback issue has a fix in #511. I'm not sure why it's desirable to change the key to a float; that doesn't really make sense. If you have another idea about how to solve this problem, please feel free to open an issue to discuss!

**Pull request closed without merging**
