### PR TITLE
Added setPan behavior for android

### PR DESCRIPTION
**Pull request by rafaelrpinto**
This PR adds an implementation of setPan for android based on an existing suggestion: https://github.com/zmxv/react-native-sound/issues/70

### CODE REVIEW

**Comment by IgorMing** [comment]
Please guys, resolve those possible conflicts and approve this pull request.
I'm waiting for this solution anxiously.

**Comment by rafaelrpinto** [comment]
@IgorMing 
Conflicts resolved. But this PR has been open for a while without feedback so instead of waiting I recommend you use this other library to achieve panning as I added the behaviour there too: https://github.com/react-native-community/react-native-video/pull/1051

**Comment by IgorMing** [comment]
Thank you very much @rafaelrpinto
Let's wait if they will approve this PR. I think I will vendor this lib inside my project, if necessary.
At least until they don't merge this.

**Review by MKrupauskas — APPROVED** [review]
I wonder if the isWindows seVolume check is done correctly but people have been waiting for this since 2016

**Pull request merged**
