### PR TITLE
first commit with windows features

### PR DESCRIPTION
**Pull request by TheGhoul21**

### CODE REVIEW

**Comment by TheGhoul21** [comment]
tested the library on the simulator with https://github.com/zmxv/react-native-sound-demo and works well

**Comment by benvium** [comment]
Looks great - could you update the README.md to describe what is working so far?

**Comment by zmxv** [comment]
Thanks for the PR! I don't have a Windows dev machine to test it, but I'm going to merge the changes and let other users to give it a try.

**Comment by TheGhoul21** [comment]
I did test with emulator on Windows 10 and works great! I'll probably do more testing when I get a physical device with WP on it, but things should be fine for now (as there's little to no actual support on ReactNative Windows)

**Pull request merged**
