### PR TITLE
On Loaded Listener

### PR DESCRIPTION
**Pull request by bighitbiker3**
Adds an `on` method to execute a callback when the sound is loaded.

### CODE REVIEW

**Comment by cavilaho** [comment]
Is this PR actually working? I mean, where do you call the `onLoaded` callback?
The `isLoaded` method seems not working on master branch, and this PR could be the solution.

**Comment by bighitbiker3** [comment]
@cavilaho Yea it's working.  The `isLoaded` method just returns a Boolean and actually is working.  I just thought there should be something that takes a callback function and does something on load.  You can use it like this: 

```
whoosh.on('loaded', function(){
    whoosh.play()
})
```

The callback is called when the sound is loaded on line 43.  The method allows for multiple events so it runs all the functions registered in the `_events.loaded` array.

**Comment by benvium** [comment]
There's a callback in the constructor that lets you know when it's loaded. Do you have a use case for this that's not covered by the constructor callback?

**Comment by fadookie** [comment]
@benvium the constructor callback is called `onError` which is misleading. I didn't even notice it was called in non-error conditions until I read through the code again just now. So perhaps it should be renamed to `onLoaded` with some examples in the docs?

**Comment by benvium** [comment]
@fadookie Yeah, I see what you mean. The readme does say '// loaded successfully' in the callback but it could indeed be made clearer.

**Comment by zmxv** [comment]
I agree that onError isn't an apt name. Nevertheless, this PR is redundant.

**Pull request closed without merging**
