### PR TITLE
fix prepareAsync called in state 8, mPlayer(0xd38e8800)

### PR DESCRIPTION
**Pull request by lekenny**
[#146](https://github.com/zmxv/react-native-sound/issues/146)

### CODE REVIEW

**Comment by benvium** [comment]
I believe this should be covered by #169 now

**Comment by benvium** [comment]
I'm closing this for now. Let me know if this is still a problem in 0.10.2 and I'll re-open if so

**Comment by karthikmit** [comment]
Looks this is happening in 0.10.4 ... Please check ..

**Comment by gvenk** [comment]
@karthikmit what's the issue you're having? Maybe you can open a new issue for this?

**Pull request closed without merging**
