### PR TITLE
Added setPitch(float) option to change pitch of the sound in Android

### PR DESCRIPTION
**Pull request by ketn**
… Also added getSpeed() and getPitch().

### CODE REVIEW

**Comment by Ketn** [comment]
Here default pitch is 1. Value of pitch between 0 & 1 produces low pitch of the given sound and above 1 produces high pitch of the given sound.

Works on API 23 and above in android.

**Comment by DavidCow** [comment]
Hi Ketn. Is it possible to map the pitch to these frequencies somehow? http://pages.mtu.edu/~suits/notefreqs.html

**Comment by sonicsmith** [comment]
This is fantastic. Please merge this in someone! @DavidCow I think keeping `setPitch` simple like it is here would be better, since to make the output match a certain note, you would need to know the pitch of the original sample.

**Comment by nriccar** [comment]
No merge?

**Comment by nriccar** [comment]
Any plans on changing pitch on iOS too?

**Comment by xbaldiq** [comment]
> Any plans on changing pitch on iOS too?

I'm looking for the same feature, what do you are ended up using?

**Comment by nriccar** [comment]
@xbaldiq did you manage to solve it?

**Comment by Fahad-pnw** [comment]
any updates to having an option to tweak the pitch? anyone has a solution to this? i need to change pitch on my notes?

**Pull request merged**
