### PR TITLE
playing the iTunes Asset URL.

### PR DESCRIPTION
**Pull request by kurokky**
II dealt with for iTunes asset URL and checked.

### CODE REVIEW

**Comment by gvenk** [comment]
There was already a PR for handeling ipod-library urls, but I think this one is better.

The other one is: https://github.com/zmxv/react-native-sound/pull/180

**Comment by kurokky** [comment]
Hi, I checked #180. 
But it was not possible playing sound on my iPhone.

**Comment by themakerman** [comment]
Why is this still not working? I am unable to play anything from my itunes library on iphone.

**Comment by kurokky** [comment]
Is it not DRM file?

Did you set "NSAppleMusicUsageDescription" key in info.plist?
And, Did you check Line 189 to 192 of the latest file "RNSound.m"?
https://github.com/zmxv/react-native-sound/blob/master/RNSound/RNSound.m

It's not latest If you find the difference.

My project is correct working that using RNSound on iPhone.

**Comment by trepidity** [comment]
@themakerman Steps to reproduce?

**Comment by themakerman** [comment]
@trepidity ok i am going to have a look in it today.

**Pull request merged**
